export const mockDataPerson = {
  name: 'Frank',
  birth_year: '785',
  created: '159',
  edited: '148',
  eye_color: 'blue',
  gender: 'male',
  hair_color: 'blond',
  height: '148',
  homeworld: 'Mars',
  mass: ' 123',
  skin_color: 'light',
  url: 'http: test.com',
};

export const mockDataPeople = [
  {
    name: 'Frank',
    birth_year: '785',
    created: '159',
    edited: '148',
    eye_color: 'blue',
    gender: 'male',
    hair_color: 'blond',
    height: '148',
    homeworld: 'Mars',
    mass: ' 123',
    skin_color: 'light',
    url: 'http: test.com',
  },
  {
    name: 'Henry',
    birth_year: '787',
    created: '154',
    edited: '144',
    eye_color: 'blue',
    gender: 'male',
    hair_color: 'black',
    height: '147',
    homeworld: 'Venera',
    mass: ' 126',
    skin_color: 'light',
    url: 'http: test.com',
  },
];
